services:
  - type: web
    name: ebook-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ebook_admin.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ebook-db
          property: connectionString

databases:
  - name: ebook-db
