# Generated by Django 5.2.4 on 2025-07-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AudioBookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Страница')),
                ('audio_tag', models.FloatField(verbose_name='Метка аудио')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('file', models.FileField(upload_to='audios/', verbose_name='Аудиофайл')),
                ('audio_type', models.CharField(choices=[('main', 'Основное'), ('repeat', 'Повторение')], default='main', max_length=10, verbose_name='Тип аудио')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.electronicbook', verbose_name='Электронная книга')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
