# Generated by Django 5.2.4 on 2025-07-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_electronicbook_audiobookfile_delete_audiofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
                ('grade', models.CharField(max_length=10, verbose_name='Класс')),
                ('who', models.CharField(choices=[('Учитель', 'Учитель'), ('Ученик', 'Ученик')], max_length=20, verbose_name='Для кого')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=20, verbose_name='Страница')),
                ('audio_mark', models.CharField(max_length=20, verbose_name='Метка аудио')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('audio_file', models.FileField(upload_to='audios/', verbose_name='Аудиофайл')),
                ('audio_type', models.CharField(choices=[('Основное', 'Основное'), ('Повторение', 'Повторение')], max_length=20, verbose_name='Тип аудио')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.ebook', verbose_name='Электронная книга')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioBookFile',
        ),
        migrations.DeleteModel(
            name='ElectronicBook',
        ),
    ]
